exports.seed = async function (knex) {
  await knex("challenge").del();
  await knex("game").del();

  await knex("game").insert([
    {
      title: "The Elder Scrolls V: Skyrim",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tnw.webp",
      year: 2011,
      genre: ["RPG", "Adventure"],
      themes: ["Action", "Fanatasy", "Open world", "Sandbox", "Stealth"],
      console: ["PC", "PlayStation 3", "Xbox 360"],
      developer: ["Bethesda Game Studios"],
      publisher: ["Bethesda Softworks"],
    },
    {
      title: "Super Mario World 2: Yoshi's Island",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co2kn9.webp",
      year: 1995,
      genre: ["Platform"],
      themes: ["Action", "Fantasy", "Kids"],
      console: ["Satellaview", "Super Famicom", "SNES"],
      developer: ["Nintendo"],
      publisher: ["Nintendo", "Hyundai", "St. GIGA", "Playtronic"],
    },
    {
      title: "Final Fantasy X",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tr1.webp",
      year: 2001,
      genre: ["RPG", "Adventure"],
      themes: ["Drama", "Fantasy", "Romance", "Science fiction"],
      console: ["PlayStation 2"],
      developer: ["Square Product Development Division 1"],
      publisher: ["Square Electronic Arts", "Square"],
    },
    {
      title: "Super Mario World",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co65za.webp",
      year: 1990,
      genre: ["Platform", "Adventure"],
      themes: ["Action", "Fantasy"],
      console: [
        "Super Famicon",
        "SNES",
        "Arcarde",
        "Wii",
        "Wii U",
        "New Nintendo 3DS",
      ],
      developer: ["Nintendo"],
      publisher: ["Nintendo", "Playtronic", "Gradiente", "Hyundai"],
    },
    {
      title: "Final Fantasy VII",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co2kx2.webp",
      year: 1997,
      genre: ["RPG", "TBS", "Adventure"],
      themes: ["Fantasy", "Science Fiction"],
      console: [
        "PlayStation",
        "PlayStation 3",
        "PlayStation Portable",
        "PlayStation Vita",
      ],
      developer: ["Square Product Development Division 1"],
      publisher: ["Sony Computer Entertainment", "Square Enix", "Square"],
    },
    {
      title: "The Witcher 3: Wild Hunt",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.webp",
      year: 2015,
      genre: ["RPG", "Adventure"],
      themes: ["Action", "Fantasy", "Open World"],
      console: [
        "Nintendo Switch",
        "PC",
        "PlayStation 4",
        "PlayStation 5",
        "Xbox One",
        "Xbox Series XIS",
      ],
      developer: ["CD Projekt RED"],
      publisher: [
        "WB Games",
        "cdp.pl",
        "Spike ChunSoft",
        "Bandai Namco Entertainment",
      ],
    },
    {
      title: "The Last of Us Part I",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co5xex.webp",
      year: 2022,
      genre: ["Shooter", "Adventure"],
      themes: ["Action", "Horror", "Stealth", "Survival"],
      console: ["PC", "PlayStation 5"],
      developer: ["Naughty Dog"],
      publisher: ["Sony Interactive Entertainment"],
    },
    {
      title: "The Legend of Zelda: Tears of the Kingdom",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co5vmg.webp",
      year: 2023,
      genre: ["RPG", "Adventure"],
      themes: ["Action", "Fantasy", "Open world", "Science Fiction"],
      console: ["Nintendo Switch"],
      developer: ["Nintendo"],
      publisher: ["Nintendo"],
    },
    {
      title: "Mass Effect Trilogy",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co4a7a.webp",
      year: 2012,
      genre: ["Shooter", "RPG"],
      themes: ["Action"],
      console: ["PlayStation 3", "Xbox"],
      developer: ["BioWare"],
      publisher: ["Electronic Arts"],
    },
    {
      title: "Elden Ring",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.webp",
      year: 2022,
      genre: ["RPG", "Adventure"],
      themes: ["Action", "Fantasy", "Open world"],
      console: [
        "PC",
        "PlayStation 4",
        "PlayStation 5",
        "Xbox One",
        "Xbox Series XIS",
      ],
      developer: ["FromSoftware"],
      publisher: ["Bandai Namco Entertainment", "FromSoftware"],
    },
    {
      title: "Baldur's Gate 3",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co670h.webp",
      year: 2023,
      genre: ["RPG", "Strategy", "TBS", "Tactical", "Adventure"],
      themes: ["Action", "Fantasy"],
      console: [
        "Google Stadia",
        "Mac",
        "PC",
        "PlayStation 5",
        "Xbox Series XIS",
      ],
      developer: ["Larian Studios"],
      publisher: ["Larian Studios"],
    },
    {
      title: "Steins;Gate",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co5ff7.webp",
      year: 2009,
      genre: ["Adventure", "Visual Novel"],
      themes: [
        "Fantasty",
        "Historical",
        "Mystery",
        "Science Fiction",
        "Survival",
      ],
      console: [
        "Android",
        "IOS",
        "PC",
        "PlayStation 3",
        "PlayStation 4",
        "PlayStation Portable",
        "PlayStation Vita",
        "Xbox 360",
      ],
      developer: ["MAGES", "Nitroplus", "5pb"],
      publisher: ["PQube", "JAST USA", "MAGES", "Kadokawa Shoten", "5pb"],
    },
    {
      title: "Persona 5 Royal",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co1nic.webp",
      year: 2019,
      genre: ["RPG", "TBS", "Adventure"],
      themes: ["Action", "Fantasy"],
      console: [
        "Nintendo Switch",
        "PC",
        "PlayStation 4",
        "PlayStation 5",
        "Xbox One",
        "Xbox Series XIS",
      ],
      developer: ["Atlus", "P Studio"],
      publisher: ["Sega"],
    },
    {
      title: "Contra",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co4ben.webp",
      year: 1988,
      genre: ["Shooter", "Platform", "Arcade"],
      themes: ["Action", "Science Fiction"],
      console: ["Arcade", "NES"],
      developer: ["Konami"],
      publisher: ["Konami"],
    },
    {
      title: "Animal Crossing",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wmn.webp",
      year: 2001,
      genre: ["Simulator"],
      themes: ["Kids", "Sandbox"],
      console: ["GameCube", "Nintendo Switch"],
      developer: ["Nintendo"],
      publisher: ["Nintendo"],
    },
    {
      title: "Persona 4",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co1u07.webp",
      year: 2008,
      genre: ["Quiz/Trivia", "RPG", "Simulator", "Visual Novel"],
      themes: ["Comedy", "Drama", "Educational", "Fantasy", "Open World"],
      console: ["PlayStation 2", "PlayStation 3"],
      developer: ["Atlus"],
      publisher: ["Atlus", "Ubisoft Australia", "Square Enix", "NIS America"],
    },
    {
      title: "The Sims",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co5qxa.webp",
      year: 2000,
      genre: ["RPG", "Simulator", "Strategy", "Adventure"],
      themes: ["Comedy", "Fantasy", "Romance", "Sandbox"],
      console: ["PC", "Mac", "Linux"],
      developer: ["Maxis"],
      publisher: ["Electronic Arts", "TransGaming Technology", "Aspyr Media"],
    },
    {
      title: "Chrono Trigger",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co3plw.webp",
      year: 1995,
      genre: ["RPG", "Adventure"],
      themes: ["Fantasy", "Open World", "Science Fiction"],
      console: ["Satellaview", "Super Famicon", "SNES", "Wii"],
      developer: ["Square", "Bird Studio"],
      publisher: ["Square"],
    },
    {
      title: "Stardes Valley",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/xrpmydnu9rpxvxfjkiu7.webp",
      year: 2016,
      genre: ["RPG", "Simulator", "Strategy", "Indie"],
      themes: ["Business", "Fantasy", "Romance", "Sandbox"],
      console: [
        "Android IOS",
        "Linux",
        "Mac",
        "Nintendo Switch",
        "PC",
        "PlayStation 4",
        "PlayStation Vita",
        "Wii U",
        "Xbox One",
      ],
      developer: ["ConcernedApe"],
      publisher: ["ConcernedApe", "Chucklefish Games"],
    },
    {
      title: "Gothic II",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co25ag.webp",
      year: 2002,
      genre: ["RPG", "Strategy", "Adventure"],
      themes: [
        "Action",
        "Fantasy",
        "Horror",
        "Open World",
        "Stealth",
        "Survival ",
      ],
      console: ["PC"],
      developer: ["Pirahna Bites"],
      publisher: [
        "JoWooD Entertainment AG",
        "Nordic Games Publishing",
        "Atari.Inc",
      ],
    },
    {
      title: "Batman: Arkham City",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co1voh.webp",
      year: 2011,
      genre: ["Hack and Slash", "Beat'em Up", "Adventure"],
      themes: [""],
      console: [
        "Nintendo Switch",
        "OnLive Game System",
        "PC",
        "PlayStation 3",
        "Xbox 360",
      ],
      developer: ["Rocksteady Studios"],
      publisher: ["WB Games", "DC Entertainment"],
    },
    {
      title: "Yakuza 0",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co252x.webp",
      year: 2015,
      genre: ["RPG", "Simulator", "Hack and Slash", "Beat'em Up", "Adventure"],
      themes: ["Action", "Drama", "Historical", "Open World"],
      console: ["PlayStation 3", "PlayStation 4", "PC", "Xbox One"],
      developer: ["Ryū Ga Gotoku Studios", "Sega Games"],
      publisher: ["Sega"],
    },
    {
      title: "Kingdom Hearts II",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co30t1.webp",
      year: 2005,
      genre: ["RPG", "Adventure"],
      themes: ["Action", "Fantasy"],
      console: ["PlayStation 2"],
      developer: [
        "Square Enix Product",
        "Development Division 1",
        "Square Enix Business",
        "Division 3",
      ],
      publisher: [
        "Buena Vista Games",
        "Sony Computer",
        "Entertainment Europe",
        "Square Enix",
      ],
    },
    {
      title: "Diablo II",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co3gfq.webp",
      year: 2000,
      genre: ["RPG", "Hack and Slash", "Beat'em Up"],
      themes: ["Action", "Fantasy"],
      console: ["Mac", "PC"],
      developer: ["Blizzard North"],
      publisher: ["Blizzard Entertainment"],
    },
    {
      title: "Grand Theft Auto: San Andreas",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lb9.webp",
      year: 2004,
      genre: ["Shooter", "Racing", "Adventure"],
      themes: ["Action", "Open World", "Stealth"],
      console: [
        "Android",
        "IOS",
        "Mac",
        "PC",
        "PlayStation 2",
        "PlayStation 3",
        "PlayStation 4",
        "Xbox",
        "Xbox 360",
      ],
      developer: ["TransGaming Inc.", "Rockstar North"],
      publisher: ["Take-Two Interactive", "Rockstar Games"],
    },
    {
      title: "Paper Mario: The Thousand-Year Door",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co25us.webp",
      year: 2004,
      genre: ["Role-playing (RPG)", "TBS", "Adventure"],
      themes: ["Action", "Comedy", "Fantasy", "Science Fiction"],
      console: ["Nintendo GameCube"],
      developer: ["Intelligent Systems"],
      publisher: ["Nintendo"],
    },
    {
      title: "Metal Gear Solid 3: Subsistence",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co1vd6.webp",
      year: 2005,
      genre: ["Shooter", "Tactical", "Adventure"],
      themes: ["Action", "Fantasy"],
      console: ["PlayStation 2"],
      developer: [
        "Konami Computer",
        "Entertainment Japan",
        "Kojima Productions",
      ],
      publisher: ["Konami"],
    },
    {
      title: "Sonic the Hedgehog",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co6yzr.webp",
      year: 1991,
      genre: ["Platform"],
      themes: ["Action", "Fantasy", "Science Fiction"],
      console: [
        "Arcade",
        "IOS",
        "PC",
        "PlayStation 3",
        "Sega Genesis",
        "Wii",
        "Xbox 360",
      ],
      developer: ["Sonic Team"],
      publisher: ["Sega", "Tec Toy"],
    },
    {
      title: "Crash Bandicoot 2: Cortex Strickes Back",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co82vt.webp",
      year: 1997,
      genre: ["Platform", "Adventure"],
      themes: ["Action", "Science Fiction", "Fantasy", "Comedy"],
      console: [
        "PlayStation",
        "PlayStation 3",
        "PlayStation Portable",
        "PlayStation Vita",
      ],
      developer: ["Naughty Dog"],
      publisher: [
        "Sony Computer",
        "Entertainment",
        "Universal Interactive Studios",
        "Sony Interactive",
        "Entertainment",
      ],
    },
    {
      title: "Diablo",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co3ggo.webp",
      year: 1996,
      genre: ["RPG", "Strategy"],
      themes: ["Action", "Fantasy", "Historical", "Horror"],
      console: ["Mac", "PC", "PlayStation"],
      developer: ["Blizzard North"],
      publisher: [
        "Electronic Arts",
        "Blizzard Entertainment",
        "Sourcenext",
        "Square Electronic Arts",
      ],
    },
    {
      title: "Resident Evil 2",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vz0.webp",
      year: 1998,
      genre: ["Shooter", "Adventure"],
      themes: ["Action", "Horror", "Survival"],
      console: [
        "Dreamcast",
        "Nintendo GameCube",
        "PC",
        "PlayStation",
        "PlayStation 3",
        "PlayStation Portable",
        "PlayStation Vita",
      ],
      developer: ["Capcom Planning Room 2"],
      publisher: ["Nintendo", "Virgin Interactive", "Entertainment", "Capcom"],
    },
    {
      title: "Silent Hill",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vye.webp",
      year: 1999,
      genre: ["Puzzle", "Adventure"],
      themes: ["Action", "Horror", "Survival"],
      console: [
        "PlayStation",
        "PlayStation 3",
        "PlayStation Portable",
        "PlayStation Vita",
      ],
      developer: ["Team Silent"],
      publisher: ["Konami"],
    },
    {
      title: "Tekken 3",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co3tsh.webp",
      year: 1997,
      genre: ["Fighting"],
      themes: ["Action"],
      console: ["Arcade", "PlayStation"],
      developer: ["Namco"],
      publisher: ["Sony Computer", "Entertainment", "Namco Hometek", "Namco"],
    },
    {
      title: "Doom",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co5rav.webp",
      year: 1993,
      genre: ["Shooter"],
      themes: ["Action", "Horror", "Science Fiction"],
      console: ["DOS", "iOS", "Linux", "Mac", "PC-9800 Series"],
      developer: ["id Software"],
      publisher: [
        "Activision",
        "id Software",
        "GT Interactive Softaware",
        "Wiz Technology",
      ],
    },
    {
      title: "GoldenEye 007",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co62k0.webp",
      year: 1997,
      genre: ["Shooter"],
      themes: ["Action", "Stealth"],
      console: ["Nintendo 64"],
      developer: ["Rare"],
      publisher: ["Nintendo", "Gradiente"],
    },
    {
      title: "Kirby Super Star",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co4qyi.webp",
      year: 1996,
      genre: ["Platform", "Adventure"],
      themes: ["Action"],
      console: ["Super Famicom", "SNES", "Wii", "Wii U"],
      developer: ["HAL Laboratory"],
      publisher: ["Nintendo", "Playtronic"],
    },
    {
      title: "Tetris",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ufk.webp",
      year: 1989,
      genre: ["Puzzle", "Arcade"],
      themes: ["Arcade", "Puzzle"],
      console: ["NES"],
      developer: ["Nintendo"],
      publisher: ["Nintendo", "Playtronic"],
    },
    {
      title: "Pokemon Gold Version",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co5pia.webp",
      year: 1999,
      genre: ["RPG", "TBS", "Adventure"],
      themes: ["Action", "Fantasy", "Kids"],
      console: ["Game Boy Color", "Nintendo 3DS"],
      developer: ["Game Freak"],
      publisher: ["Gradiente", "Nintendo"],
    },
    {
      title: "Sonic the Hedgehog 2",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co5kkj.webp",
      year: 1992,
      genre: ["Platform"],
      themes: ["Action", "Science Fiction"],
      console: [
        "Nintendo 3DS",
        "PC",
        "PlayStation 3",
        "Sega Genesis",
        "Wii",
        "Wii U",
        "Xbox 360",
      ],
      developer: ["Sega Technical Institute", "Sonic Team"],
      publisher: ["Sega", "Tec Toy"],
    },
    {
      title: "Donkey Kong Country 2: Diddy's Kong Quest",
      imagesrc:
        "https://images.igdb.com/igdb/image/upload/t_cover_big/co217m.webp",
      year: 1995,
      genre: ["Platform", "Adventure"],
      themes: ["Action", "Comedy", "Fantasy"],
      console: ["New Nintendo 3DS", "Super Famicom", "SNES", "Wii", "Wii U"],
      developer: ["Rare"],
      publisher: ["Nintendo", "Gradiente", "Platronic", "Hyundai"],
    },
  ]);
};
